version: "3.9"

services:
  database:
    image: mysql/mysql-server:8.0
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_DATABASE=fmb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=ZzO8J18glzYPM71
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - symfony_network
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: symfony_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - symfony_network

  nginx:
    image: nginx:1.27
    container_name: symfony_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_network

volumes:
  php_socket:
  mysql-volume:
    driver: local

networks:
  symfony_network:
    driver: bridge