apiVersion: v1
kind: Service
metadata:
  name: {{ include "your-chart-name.fullname" . }}
  labels:
    app: {{ include "your-chart-name.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "your-chart-name.name" . }}